environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -m pip install -U pip
  - pip install -r requirements.txt
  - pip install win-unicode-console

build: off

test_script:
  - pythom -m pytest -v -s --cov
