environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip"
  - "pip install -r requirements.txt"

build: off

test_script:
  # https://stackoverflow.com/a/32383309/9800909
  - "chcp 65001 & pytest -v -s --cov"
