environment:
  PYTHONIOENCODING: UTF-8
  matrix:
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38

build: off

install:
  - python3 -m pip install tox

test_script:
  - python3 -m tox
