sudo: false
language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - export LOG_LEVEL=DEBUG
install:
  - travis_wait 20 mvn install
  - pip install tox-travis
script:
  - tox
after_success:
  - coveralls
