sudo: false
language: python

matrix:
  include:
    - os: linux
      python: 3.5
      env:
        - PYENV=py35
        - PYTHON=python
        - PIP=pip
    - os: linux
      python: 3.6
      env:
        - PYENV=py36
        - PYTHON=python
        - PIP=pip
    - os: osx
      language: generic
      env:
        - PYENV=py35
        - PYTHON=python3
        - PIP=pip3
    - os: osx
      language: generic
      env:
        - PYENV=py36
        - PYTHON=python3
        - PIP=pip3

before_install:
  - export LOG_LEVEL=DEBUG
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew update || true ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ $PYENV == py35 ] ; then brew install python35 || true ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ $PYENV == py36 ] ; then brew install python36 || true ; fi
  - $PYTHON --version
  - $PYTHON -m pip install -U pip
  - $PIP install -r requirements.txt
  - $PIP install coveralls
before_script:
  - $PYTHON -m coverage erase
script:
  - $PYTHON -m pytest -v -s --cov
after_success:
  - $PYTHON -m coveralls
