sudo: false
language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
        env: TOXENV=py36
before_install:
  - export LOG_LEVEL=DEBUG
install:
  - pip install coverage coveralls
before_script:
  - coverage erase
script:
  - tox
after_success: coverage combine && coverage report && coveralls
