sudo: false
language: python

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env: PYENV_VERSION=3.5.4
    - os: osx
      language: generic
      env: PYENV_VERSION=3.6.8

before_install:
  - export LOG_LEVEL=DEBUG
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew outdated pyenv || brew upgrade pyenv ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then pyenv install $PYENV_VERSION ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then ~/.pyenv/versions/$PYENV_VERSION/bin/python -m venv .venv ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then source .venv/bin/activate ; fi
  - python --version
  - python -m pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python -m coverage erase
script:
  - python --version
  - python -m pytest -v -s --cov
after_success:
  - python -m coveralls
