sudo: false
language: python
python:
  - "cov-init"
  - "3.5"
  - "3.6"
  - "cov-report"
before_install:
  - export LOG_LEVEL=DEBUG
install:
  - pip install tox-travis
env:
  - PUBLISH_COVERAGE_COMMAND=coveralls
script:
  - tox
