sudo: false
language: python

matrix:
  include:
    - os: linux
      python: 3.5
      env: PYENV=py35
    - os: linux
      python: 3.6
      env: PYENV=py36
    - os: osx
      language: generic
      env: PYENV=py35
    - os: osx
      language: generic
      env: PYENV=py36

before_install:
  - export LOG_LEVEL=DEBUG
install:
  - ./.ci/travis/install.sh
before_script:
  - coverage erase
script:
  - pytest -v -s --cov
after_success:
  - coveralls
