sudo: false
language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - export LOG_LEVEL=DEBUG
install:
  - pip install tox-travis coverage
before_script:
  - coverage erase
script:
  - tox
after_success: coverage combine && coverage report && coveralls
