sudo: false
language: python

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env:
        - PYENV_VERSION=3.5.4
    - os: osx
      language: generic
      env:
        - PYENV_VERSION=3.6.8

before_install:
  - export LOG_LEVEL=DEBUG
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then which pyenv || true ; fi
install:
  #- if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew update || true ; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew install openssl readline || true ; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew outdated pyenv || brew upgrade pyenv || true ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew install pyenv-virtualenv || true ; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ] ; then export PYENV_ROOT="$HOME/.pyenv" || true ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then pyenv install $PYENV_VERSION || true ; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ] ; then export PATH="$PYENV_ROOT/bin:$PATH" || true ; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ] ; then eval "$(pyenv init -)" || true ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then eval "$(pyenv virtualenv-init -)" || true ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then pyenv-virtualenv venv || true ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then source venv/bin/activate || true ; fi
  - python --version
  - python -m pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python -m coverage erase
script:
  - python --version
  - pyenv versions
  - python -m pytest -v -s --cov
after_success:
  - python -m coveralls
